{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-conflicted
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/conflicted_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/conflicted/conflicted_{{ version }}.tar.gz
  sha256: c99b86bb52da3e7d1f4d96d70c77304d0434db5bd906edd8d743e89ac9223088

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli >=3.4.0
    - r-memoise
    - r-rlang >=1.0.0
  run:
    - r-base
    - r-cli >=3.4.0
    - r-memoise
    - r-rlang >=1.0.0

test:
  commands:
    - $R -e "library('conflicted')"           # [not win]
    - "\"%R%\" -e \"library('conflicted')\""  # [win]

about:
  home: https://conflicted.r-lib.org/
  dev_url: https://github.com/r-lib/conflicted
  doc_url: https://conflicted.r-lib.org/reference/index.html
  license: MIT
  summary: R's default conflict management system gives the most recently loaded package precedence. This can make it hard to detect conflicts,  particularly when they arise because a package update creates ambiguity that did not previously exist. 'conflicted' takes a different approach,  making every conflict an error and
    forcing you to choose which function  to use.
  license_family: MIT
  license_file: 
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Date/Publication: 2019-03-29 22:10:06 UTC
