{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-conflicted
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/conflicted_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/conflicted/conflicted_{{ version }}.tar.gz
  sha256: c99b86bb52da3e7d1f4d96d70c77304d0434db5bd906edd8d743e89ac9223088

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-memoise
    - r-rlang
  run:
    - r-base
    - r-memoise
    - r-rlang

test:
  commands:
    - $R -e "library('conflicted')"           # [not win]
    - "\"%R%\" -e \"library('conflicted')\""  # [win]

about:
  home: https://github.com/r-lib/conflicted
  license: GPL-3.0-only
  summary: R's default conflict management system gives the most recently loaded package precedence. This can make it hard to detect conflicts,  particularly when they arise because a package update creates ambiguity that did not previously exist. 'conflicted' takes a different approach,  making every conflict an error and
    forcing you to choose which function  to use.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: conflicted
# Title: An Alternative Conflict Resolution Strategy
# Version: 1.0.2
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph") )
# Description: R's default conflict management system gives the most recently loaded package precedence. This can make it hard to detect conflicts,  particularly when they arise because a package update creates ambiguity that did not previously exist. 'conflicted' takes a different approach,  making every conflict an error and forcing you to choose which function  to use.
# License: GPL-3
# URL: https://github.com/r-lib/conflicted
# BugReports: https://github.com/r-lib/conflicted/issues
# Depends: R (>= 3.2)
# Imports: rlang, memoise
# Suggests: covr, crayon, dplyr, pkgdown, testthat
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-03-29 21:56:55 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-03-29 22:10:06 UTC
