appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: nMLb3skNwsPONxNnhfsWQuyvZMZDLVin4w3mIUKoz/7yRYwQVBcEdTqee+FtgPWi+wE8z5eG6PqwDRyl3OgJz4eG0r/14M6yagtNPFgJshTqwDV0FEQvLK1Z+8CP7UQFs01SpEwrqXJD/EwCgAB8gEgVmY8HR+1dQM+i9BrM/QM8L0SCTz3UgviEjYO4/oSZArArItHduP4J1kBY6qdQlcNkBYIJljczHVi5vWhX0CIBagf3iioILGE1ubQgcMvZU9T7jj+VaxlrNoSRMlMjsBYng0RxtYbdPQaKIgXoYfmz2nJJHSEGnHbupXK6itU3tDlw1zGsF/RcDbjebB2teg0tYgzFwQIzdO7mR+KqOZ2x3/VYDirZnq80iWwpNVu92t+xQvmVy/go+iehPN4dKaSBKIqIEfGilVHKSEBRTsmxMPZ1auGGdn+w8HJDNsrYMXbRDAUJSBGYzivXTan3CFYvwkfp3No2hl2XZHeScv9bDBmpLTTsfnu4QMBR+7wH2l6pEA2gwyw/BR+1KX7gSeRrvaDvV3TlvjpCz8Lb0LsujFURzeBn9Nmo5RwhyXizd5erGhgSXpSqBP/wGAKbLVJ7aeFofqy+ZLpbeDdsLeZ2Dmg1+JJm9dnL6cYAsyOfjQ34atbBfOdKq72zf9oKRJHGpgs4Gwe1orEnEV44CCM=}
